### ISSUE TITLE
when will the code be updated

### ISSUE THREAD

**Issue by 156aasdfg** [yuleiniu/introd#1]
hi thanks a lot for your awesome  work in overcoming bias.  Can't wait to see your code！！！ 🙊😘Waiting for your update！

**Comment by yuleiniu** [comment]
Thank you for your interest. We have just updated the codes.

**Comment by 156aasdfg** [comment]
thanks for your code. Your paper is very well written. The reading experience is very good. I am also a master student in this field. I will quote your papers in the future. Although I have cited cfvqa this paper twice. Look forward to your future papers
